[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=1
HidePrompt=1
UseLongFileName=1
InsideCompressed=1
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\Users\trevo\Desktop\FOS\FOS.exe
FriendlyName=FOS
AppLaunched=FOS.bat
PostInstallCmd=<None>
SourceFiles=SourceFiles
[SourceFiles]
SourceFiles0=C:\Users\trevo\Desktop\FOS
[SourceFiles0]
FOS.ps1=
FOS_Startup.ps1=
PlayFabConfig.json=
FOS.bat=
